<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" align="left" hspace="10px" vspace="0px"></p>

<h1> Python</h1>

www.python.org - www.python.org

<h1> Fundamentos en Computación</h1>

Profs: Andrés F. Rivera R.


# Numpy
https://numpy.org/

<p><img alt="numpy logo" height="250px" src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" align="left" hspace="10px" vspace="0px"></p>



**¿Qué es?**
*   NumPy (**Numerical Python**) es una librería numérica de Python que proporciona estructuras de datos matriciales y funciones matemáticas de alto nivel.
*   ..

**¿Para qué?**


*    Podrás realizar operaciones numéricas de manera muy sencilla.
*   A simple vista parace como las listas de Python pero con Numpy es (hacer los mismo), pero hay 3 grandes diferencias: 


1.   Las estructuras de datos de NumPy ocupan menos espacio en memoria que las listas.
2. Es más rápido. Esto es porque NumPy está escrito en su mayor parte en C (especial para lidiar con grandes cantidades de datos).
3. NumPy tiene programadas muchas funciones que en Python tendríamos que programar con ciclos y muchos conceptos matemáticos.

*  Numpy es la base de **matplotlib**, **Pandas** y **Scipy** usados en Data Science.


**¿Cómo?**

*   Ver la página oficial para instalarlo (en el colab ya está instalado).
*   ...






Por convención, se importa a Python de esta manera:

In [1]:
import numpy as np

## Operaciones matemáticas básicas con Numpy

In [2]:
np.pi

3.141592653589793

In [3]:
np.sin(30*np.pi/180)

0.49999999999999994

In [ ]:
print('pi/6=',np.pi/6,'\n')

print('sin(pi/6)=',np.sin(np.pi/6),'\n')

print('log10(100)=',np.log10(100),'\n')

print('Logaritmo neperiano','log(100)=',np.log(100),'\n')

pi/6= 0.5235987755982988 

sin(pi/6)= 0.49999999999999994 

log10(100)= 2.0 

Logaritmo neperiano log(100)= 4.605170185988092 



## Arrays

NumPy trabaja con una estructura de datos llamada array o arreglos numéricos multidimensionales. 
Un array unidimensional puede ser una fila o una columna de una tabla. erstos arrays son llamados **ndarray** 

1.   Un array unidimensional puedes ser una fila o columna de una tabla, este se conoce como **vector** (rango 1). 
2. Un array bidimensional es lo que llamamos **matriz** (rango 2).
3. Y un array de 3 dimensiones (o más), es decir, se conoce como **tensor**.

ver: https://platzi.com/blog/numpy/

### Crear un array a partir de una lista:

In [4]:
mi_lista=[1,2,3,10]

In [5]:
print(mi_lista)

[1, 2, 3, 10]


In [6]:
type(mi_lista)

list

In [8]:
mi_lista=[1,2,3,10]

mi_vector = np.array(mi_lista)

mi_matriz = np.array([[1,2],[3,10]])

print(mi_vector,'\n', mi_matriz)

[ 1  2  3 10] 
 [[ 1  2]
 [ 3 10]]


In [9]:
type(mi_vector)

numpy.ndarray

... note que retorna un elemento que es un ndarray

In [ ]:
¿Cómo generar una lista de 0 a 3 con un paso de 0.2.

In [ ]:
#propuesto por un estudiante
x =[]
i=0
while i <=3.0:
  i = i + 0.2
  #print(i)

  x.append(i)

x

[0.2,
 0.4,
 0.6000000000000001,
 0.8,
 1.0,
 1.2,
 1.4,
 1.5999999999999999,
 1.7999999999999998,
 1.9999999999999998,
 2.1999999999999997,
 2.4,
 2.6,
 2.8000000000000003,
 3.0000000000000004]

### Crear array secuenciales

También puedes crear arrays con secuencias de números.


*   **np.arange(start, stop, step)**: Funciona como el range en Python, pero retorna un ndarray.
*   **np.linspace(start, stop, num)**: el step se calcula automáticamente.
*   **np.logspace()**
* ....



In [ ]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(0,3,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8])

In [13]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.logspace(-2,5,10)

array([1.00000000e-02, 5.99484250e-02, 3.59381366e-01, 2.15443469e+00,
       1.29154967e+01, 7.74263683e+01, 4.64158883e+02, 2.78255940e+03,
       1.66810054e+04, 1.00000000e+05])

Nota: Cuando se trabajan con varios ordenes de magnitud, es conveniente usar el logspace. Lo veremos luego cuando grafiquemos con matplotlib.

### **Creando arrays vacíos y predefinidos**

*   np.zeros
*   np.ones
*   np.full(shape=(a,b), fill_value=c)



In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

note que debemos pasar una tupla para varias dimensiones.

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.fives((2,2))

AttributeError: ignored

In [ ]:
np.array([[5,5],[5,5]])

array([[5, 5],
       [5, 5]])

In [ ]:
a = np.full(shape=(10, 10), fill_value=5)

In [ ]:
print(a)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


### **Arreglos aleatorios**



1. **np.random.rand()**: distribución uniforme. Permite crear ndarrays.
2. **np.random.uniform(low,hight,size)**: como rand, pero permite ingresar los límites de la muestra.
3 . **np.random.randn()**: distribución normal. Permite crear ndarrays.
4. **np.random.normal()**: como randn, pero permite escalar los límites de la muestra. warming!!!
5. **np.random.randint(low=a, high=b, size=(c,d)))**: números enteros aleatorios entre un rango dado.


ver tipos de distribuciones: https://ucreanop.com/wp-content/uploads/2021/08/06-Medir.pdf


In [ ]:
np.random.rand(3)

array([0.68260403, 0.7141163 , 0.50720514])

In [ ]:
np.random.normal(1,3,5)

array([ 1.4484762 , -2.47471573,  0.87378622,  2.04939675,  2.15765552])

In [ ]:


np.random.uniform(3)

1.8454848416063263

In [ ]:
np.random.uniform(0,3,5) #Warning

array([0.737084  , 2.34784528, 0.38408772, 0.36669744, 2.55497393])

In [ ]:
np.random.randint(0,3)

2

In [ ]:
np.random.randint(0,5,size=(2,2))

array([[1, 2],
       [3, 0]])

### **Tamaño de los arrays**




1.   **.shape:** devuelve las dimensiones del array. Para una matriz el primer valor son las filas y el segundo las columnas. Para un tensor el primer valor es la “profundidad”, el segundo las filas y el tercero las columnas.
2. **.reshape()**: redimensiona un array, es decir, te permite crear matrices o tensores a partir de vectores y viceversa. También funciona como método.
3. **.dtype**: devuelve el tipo de dato de un array.

In [19]:
mi_matriz = np.array([[1,8,5],[3,10,3],[0,5,6],[1,1,2]])
print(mi_matriz)

[[ 1  8  5]
 [ 3 10  3]
 [ 0  5  6]
 [ 1  1  2]]


In [23]:
mi_matriz.shape[1]

3

In [ ]:
a.shape

(10, 10)

### **Manipulando arrays:** índices, slicing,...

Los ndarrays permiten hacer slicing (rebanadas) con la notación [filas, columnas] y sus índices inician en 0.

Para seleccionar toda una columna o fila, se usa **:**, tal que:


*   [n, :] ← esto selecciona todas las columnas de la n-esima fila.
*   [:, n] ← selecciona todas las filas de la n-ésima columna.

Vemaos algunos ejemplos:



In [26]:
a = np.random.randint(0,10,size=(6,6))

a

array([[6, 4, 9, 2, 9, 4],
       [9, 7, 5, 7, 7, 6],
       [8, 0, 5, 3, 7, 7],
       [8, 3, 9, 1, 7, 0],
       [0, 6, 2, 1, 4, 7],
       [3, 9, 0, 0, 6, 3]])

In [40]:
x = []
for i in range(6):
  
  y = a[0,i]
  print(y)
  x.append(y)

x = np.array(x)

6
4
9
2
9
4


In [42]:
x

array([6, 4, 9, 2, 9, 4])

In [43]:
#Imprimir el elemento[1,2] (fila 1, segunda y columna 2 tercera). Python cuenta desde 0.
a[1,2]

5

In [44]:
# Imprimir todos los datos de la fila 2
a[0,:]

array([6, 4, 9, 2, 9, 4])

In [ ]:
a[2]

array([5, 9, 8, 8, 5])

In [46]:
a

array([[6, 4, 9, 2, 9, 4],
       [9, 7, 5, 7, 7, 6],
       [8, 0, 5, 3, 7, 7],
       [8, 3, 9, 1, 7, 0],
       [0, 6, 2, 1, 4, 7],
       [3, 9, 0, 0, 6, 3]])

In [49]:
# Imprimir todos los datos de la columnda 3
a[:,3]

array([2, 7, 3, 1, 1, 0])


# Resumen: Hoja de trucos

ver:

https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf


