In [1]:
Ejercicio:


SyntaxError: invalid syntax (<ipython-input-1-10a16db999a1>, line 1)

In [7]:
import numpy as np

In [9]:
x = [1,0,3,8,10,20,4]

In [11]:
x

[1, 0, 3, 8, 10, 20, 4]

In [12]:
np.sort(x)

array([ 0,  1,  3,  4,  8, 10, 20])

In [13]:
np.random.randint(1,10)

8

In [ ]:
crear lista con numeros aleatorios

crear lista con numeros aleatorios

In [18]:
x = np.random.randint(1,100,10)

In [22]:
x

array([58, 91, 10, 32, 73, 53, 85, 45, 45, 38])

In [20]:
type(x)

numpy.ndarray

In [24]:
np.sort(x)

array([10, 32, 38, 45, 45, 53, 58, 73, 85, 91])

In [38]:
y = []

for i in range(0,10):
  z = np.random.randint(1,10)
  #print(i,z)
  y.append(z)

print(y)

[9, 7, 9, 2, 4, 3, 1, 7, 7, 6]
